id: IBBCC819F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:02:16+00:00'
last_modified: '2022-06-08T05:56:20.290835+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20468
  title: ཀློང་ཆེན་པའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    36C8:
      image_group_id: I1GS105496
      title: ''
      total_pages: 258
      order: 1
      base_file: 36C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
